"""exporters.py — Export reports to PDF, CSV, and HTML."""

import csv
import json
import os
import datetime


# ── HTML Export ──────────────────────────────────────────────────────────────

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>System Report — {generated_at}</title>
<style>
  :root {{
    --bg:#0d1117; --bg2:#161b22; --bg3:#21262d;
    --accent:#00d68f; --accent2:#388bfd;
    --text:#e6edf3; --text-dim:#8b949e;
    --red:#f85149; --yellow:#d29922;
    --border:#30363d;
  }}
  * {{ box-sizing:border-box; margin:0; padding:0; }}
  body {{ background:var(--bg); color:var(--text); font-family:'Courier New',monospace; padding:2rem; }}
  h1 {{ color:var(--accent); font-size:1.6rem; letter-spacing:0.1em; margin-bottom:0.25rem; }}
  .meta {{ color:var(--text-dim); font-size:0.8rem; margin-bottom:2rem; }}
  h2 {{ color:var(--accent2); font-size:1rem; text-transform:uppercase;
        letter-spacing:0.08em; border-bottom:1px solid var(--border);
        padding-bottom:0.4rem; margin:1.5rem 0 0.75rem; }}
  table {{ width:100%; border-collapse:collapse; font-size:0.85rem; margin-bottom:1rem; }}
  th {{ background:var(--bg3); color:var(--accent); text-align:left;
        padding:0.5rem 0.75rem; border:1px solid var(--border); }}
  td {{ padding:0.4rem 0.75rem; border:1px solid var(--border); vertical-align:top; }}
  tr:nth-child(even) td {{ background:var(--bg2); }}
  .flag-yes {{ color:var(--red); font-weight:bold; }}
  .flag-no  {{ color:var(--accent); }}
  .up   {{ color:var(--accent); }}
  .down {{ color:var(--red); }}
  footer {{ margin-top:3rem; color:var(--text-dim); font-size:0.75rem; border-top:1px solid var(--border); padding-top:1rem; }}
</style>
</head>
<body>
<h1>&#128737; SYSTEM INFO &amp; GEOLOCATION REPORT</h1>
<p class="meta">Generated: {generated_at}</p>

<h2>&#128187; System</h2>
<table>
  <tr><th>Field</th><th>Value</th></tr>
  {system_rows}
</table>

<h2>&#9889; CPU</h2>
<table>
  <tr><th>Field</th><th>Value</th></tr>
  {cpu_rows}
</table>

<h2>&#128190; Memory</h2>
<table>
  <tr><th>Field</th><th>Value</th></tr>
  {memory_rows}
</table>

<h2>&#128191; Disk Partitions</h2>
<table>
  <tr><th>Device</th><th>Mount</th><th>FS</th><th>Total GB</th><th>Used GB</th><th>Free GB</th><th>Usage %</th></tr>
  {disk_rows}
</table>

<h2>&#128268; Network Interfaces</h2>
<table>
  <tr><th>Interface</th><th>Status</th><th>MAC</th><th>IP Addresses</th></tr>
  {net_rows}
</table>

<h2>&#127758; Geolocation</h2>
<table>
  <tr><th>Field</th><th>Value</th></tr>
  {geo_rows}
</table>

<footer>Report generated by SysInfo &amp; Geolocation Extractor</footer>
</body>
</html>
"""


def _tr(label, value):
    return f"<tr><td><strong>{label}</strong></td><td>{value}</td></tr>"


def export_html(report_dict: dict, filepath: str):
    s   = report_dict.get("system", {})
    c   = report_dict.get("cpu", {})
    m   = report_dict.get("memory", {})
    g   = report_dict.get("geo", {})
    ts  = report_dict.get("generated_at", "")

    sys_rows = "\n".join([
        _tr("Hostname",       s.get("hostname","")),
        _tr("OS",             f"{s.get('os_name','')} {s.get('os_release','')}"),
        _tr("Version",        s.get("os_version","")[:80]),
        _tr("Architecture",   f"{s.get('architecture','')} / {s.get('machine','')}"),
        _tr("Processor",      s.get("processor","")[:80]),
        _tr("Python",         s.get("python_version","")),
        _tr("User",           s.get("current_user","")),
        _tr("MAC Address",    s.get("mac_address","")),
        _tr("Boot Time",      s.get("boot_time","")),
    ])

    cpu_rows = "\n".join([
        _tr("Physical Cores",    c.get("physical_cores",0)),
        _tr("Logical Cores",     c.get("logical_cores",0)),
        _tr("Max Freq (MHz)",    c.get("max_freq_mhz",0)),
        _tr("Current Freq (MHz)",c.get("current_freq_mhz",0)),
        _tr("Usage %",           f"{c.get('usage_percent',0)}%"),
    ])

    mem_rows = "\n".join([
        _tr("Total (GB)",     m.get("total_gb",0)),
        _tr("Used (GB)",      m.get("used_gb",0)),
        _tr("Available (GB)", m.get("available_gb",0)),
        _tr("Usage %",        f"{m.get('percent_used',0)}%"),
    ])

    disk_rows = ""
    for d in report_dict.get("disks", []):
        disk_rows += (
            f"<tr><td>{d.get('device','')}</td><td>{d.get('mountpoint','')}</td>"
            f"<td>{d.get('fstype','')}</td><td>{d.get('total_gb',0)}</td>"
            f"<td>{d.get('used_gb',0)}</td><td>{d.get('free_gb',0)}</td>"
            f"<td>{d.get('percent_used',0)}%</td></tr>\n"
        )

    net_rows = ""
    for iface in report_dict.get("interfaces", []):
        status_cls = "up" if iface.get("is_up") else "down"
        status_lbl = "UP" if iface.get("is_up") else "DOWN"
        ips = "<br>".join(iface.get("ip_addresses", []))
        net_rows += (
            f"<tr><td>{iface.get('name','')}</td>"
            f"<td class='{status_cls}'>{status_lbl}</td>"
            f"<td>{iface.get('mac_address','—')}</td>"
            f"<td>{ips or '—'}</td></tr>\n"
        )

    proxy_cls = "flag-yes" if g.get("is_proxy") else "flag-no"
    host_cls  = "flag-yes" if g.get("is_hosting") else "flag-no"
    geo_rows = "\n".join([
        _tr("Public IP",       g.get("public_ip","")),
        _tr("Country",         f"{g.get('country','')} ({g.get('country_code','')})"),
        _tr("Region",          g.get("region","")),
        _tr("City",            g.get("city","")),
        _tr("ZIP",             g.get("zip_code","")),
        _tr("Coordinates",     f"Lat {g.get('latitude',0)}, Lon {g.get('longitude',0)}"),
        _tr("Timezone",        g.get("timezone","")),
        _tr("ISP",             g.get("isp","")),
        _tr("Org",             g.get("org","")),
        _tr("ASN",             g.get("asn","")),
        _tr("Proxy/VPN",       f"<span class='{proxy_cls}'>{'YES' if g.get('is_proxy') else 'No'}</span>"),
        _tr("Hosting/DC",      f"<span class='{host_cls}'>{'YES' if g.get('is_hosting') else 'No'}</span>"),
    ])

    html = HTML_TEMPLATE.format(
        generated_at=ts,
        system_rows=sys_rows, cpu_rows=cpu_rows,
        memory_rows=mem_rows, disk_rows=disk_rows,
        net_rows=net_rows,    geo_rows=geo_rows,
    )
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(html)


# ── CSV Export ───────────────────────────────────────────────────────────────

def export_csv(report_dict: dict, filepath: str):
    s = report_dict.get("system", {})
    c = report_dict.get("cpu", {})
    m = report_dict.get("memory", {})
    g = report_dict.get("geo", {})

    rows = [
        ["Section", "Field", "Value"],
        ["System", "Hostname",       s.get("hostname","")],
        ["System", "OS",             f"{s.get('os_name','')} {s.get('os_release','')}"],
        ["System", "Architecture",   f"{s.get('architecture','')} / {s.get('machine','')}"],
        ["System", "Processor",      s.get("processor","")],
        ["System", "Python",         s.get("python_version","")],
        ["System", "User",           s.get("current_user","")],
        ["System", "MAC",            s.get("mac_address","")],
        ["System", "Boot Time",      s.get("boot_time","")],
        ["CPU", "Physical Cores",    c.get("physical_cores","")],
        ["CPU", "Logical Cores",     c.get("logical_cores","")],
        ["CPU", "Max Freq (MHz)",    c.get("max_freq_mhz","")],
        ["CPU", "Usage %",           c.get("usage_percent","")],
        ["Memory", "Total (GB)",     m.get("total_gb","")],
        ["Memory", "Used (GB)",      m.get("used_gb","")],
        ["Memory", "Available (GB)", m.get("available_gb","")],
        ["Memory", "Usage %",        m.get("percent_used","")],
        ["Geo", "Public IP",         g.get("public_ip","")],
        ["Geo", "Country",           g.get("country","")],
        ["Geo", "Region",            g.get("region","")],
        ["Geo", "City",              g.get("city","")],
        ["Geo", "Coordinates",       f"{g.get('latitude',0)}, {g.get('longitude',0)}"],
        ["Geo", "Timezone",          g.get("timezone","")],
        ["Geo", "ISP",               g.get("isp","")],
        ["Geo", "ASN",               g.get("asn","")],
        ["Geo", "Proxy/VPN",         "Yes" if g.get("is_proxy") else "No"],
        ["Geo", "Hosting/DC",        "Yes" if g.get("is_hosting") else "No"],
    ]

    for d in report_dict.get("disks", []):
        rows.append(["Disk", d.get("device",""), f"{d.get('mountpoint','')} {d.get('fstype','')} {d.get('total_gb',0)}GB total {d.get('percent_used',0)}% used"])

    for iface in report_dict.get("interfaces", []):
        status = "UP" if iface.get("is_up") else "DOWN"
        ips = "; ".join(iface.get("ip_addresses", []))
        rows.append(["Network", iface.get("name",""), f"{status} MAC:{iface.get('mac_address','—')} IPs:{ips}"])

    with open(filepath, "w", newline="", encoding="utf-8") as f:
        csv.writer(f).writerows(rows)


# ── PDF Export ───────────────────────────────────────────────────────────────

def export_pdf(report_dict: dict, filepath: str):
    """Generate a styled PDF report using reportlab."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
        )
    except ImportError:
        raise ImportError("reportlab is required for PDF export. Run: pip install reportlab")

    doc = SimpleDocTemplate(
        filepath, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=2*cm,  bottomMargin=2*cm,
    )

    BG   = colors.HexColor("#0d1117")
    ACC  = colors.HexColor("#00d68f")
    ACC2 = colors.HexColor("#388bfd")
    RED  = colors.HexColor("#f85149")
    DIM  = colors.HexColor("#8b949e")
    WHITE= colors.HexColor("#e6edf3")
    CELL = colors.HexColor("#161b22")
    CELL2= colors.HexColor("#21262d")

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "title", fontName="Courier-Bold", fontSize=18,
        textColor=ACC, spaceAfter=4,
    )
    meta_style = ParagraphStyle(
        "meta", fontName="Courier", fontSize=8,
        textColor=DIM, spaceAfter=12,
    )
    h2_style = ParagraphStyle(
        "h2", fontName="Courier-Bold", fontSize=11,
        textColor=ACC2, spaceBefore=14, spaceAfter=4,
    )

    def section_table(header_cols, data_rows, col_widths=None):
        table_data = [header_cols] + data_rows
        t = Table(table_data, colWidths=col_widths, repeatRows=1)
        style = TableStyle([
            ("BACKGROUND",    (0,0), (-1,0),  CELL2),
            ("TEXTCOLOR",     (0,0), (-1,0),  ACC),
            ("FONTNAME",      (0,0), (-1,0),  "Courier-Bold"),
            ("FONTSIZE",      (0,0), (-1,-1), 8),
            ("FONTNAME",      (0,1), (-1,-1), "Courier"),
            ("TEXTCOLOR",     (0,1), (-1,-1), WHITE),
            ("BACKGROUND",    (0,1), (-1,-1), CELL),
            ("ROWBACKGROUNDS",(0,1), (-1,-1), [CELL, CELL2]),
            ("GRID",          (0,0), (-1,-1), 0.3, DIM),
            ("ALIGN",         (0,0), (-1,-1), "LEFT"),
            ("VALIGN",        (0,0), (-1,-1), "TOP"),
            ("LEFTPADDING",   (0,0), (-1,-1), 6),
            ("RIGHTPADDING",  (0,0), (-1,-1), 6),
            ("TOPPADDING",    (0,0), (-1,-1), 4),
            ("BOTTOMPADDING", (0,0), (-1,-1), 4),
        ])
        t.setStyle(style)
        return t

    s = report_dict.get("system", {})
    c = report_dict.get("cpu", {})
    m = report_dict.get("memory", {})
    g = report_dict.get("geo", {})
    ts = report_dict.get("generated_at", "")

    W = A4[0] - 4*cm
    col2 = [W*0.38, W*0.62]

    story = [
        Paragraph("SYSTEM INFO & GEOLOCATION REPORT", title_style),
        Paragraph(f"Generated: {ts}", meta_style),
        HRFlowable(width="100%", thickness=0.5, color=DIM),
        Spacer(1, 8),

        Paragraph("System", h2_style),
        section_table(["Field", "Value"], [
            ["Hostname",    s.get("hostname","")],
            ["OS",          f"{s.get('os_name','')} {s.get('os_release','')}"],
            ["Architecture",f"{s.get('architecture','')} / {s.get('machine','')}"],
            ["Processor",   (s.get("processor","") or "")[:70]],
            ["Python",      s.get("python_version","")],
            ["User",        s.get("current_user","")],
            ["MAC",         s.get("mac_address","")],
            ["Boot Time",   s.get("boot_time","")],
        ], col_widths=col2),

        Paragraph("CPU", h2_style),
        section_table(["Field", "Value"], [
            ["Physical Cores",    str(c.get("physical_cores",""))],
            ["Logical Cores",     str(c.get("logical_cores",""))],
            ["Max Frequency",     f"{c.get('max_freq_mhz',0)} MHz"],
            ["CPU Usage",         f"{c.get('usage_percent',0)}%"],
        ], col_widths=col2),

        Paragraph("Memory", h2_style),
        section_table(["Field", "Value"], [
            ["Total",     f"{m.get('total_gb',0)} GB"],
            ["Used",      f"{m.get('used_gb',0)} GB"],
            ["Available", f"{m.get('available_gb',0)} GB"],
            ["Usage",     f"{m.get('percent_used',0)}%"],
        ], col_widths=col2),

        Paragraph("Disk Partitions", h2_style),
        section_table(
            ["Device","Mount","FS","Total","Used","Free","Usage%"],
            [[d.get("device",""), d.get("mountpoint",""), d.get("fstype",""),
              f"{d.get('total_gb',0)}G", f"{d.get('used_gb',0)}G",
              f"{d.get('free_gb',0)}G", f"{d.get('percent_used',0)}%"]
             for d in report_dict.get("disks", [])],
            col_widths=[W*0.17]*7 if report_dict.get("disks") else None,
        ),

        Paragraph("Network Interfaces", h2_style),
        section_table(
            ["Interface","Status","MAC","IP Addresses"],
            [[i.get("name",""), "UP" if i.get("is_up") else "DOWN",
              i.get("mac_address","—"), "\n".join(i.get("ip_addresses",[]))]
             for i in report_dict.get("interfaces",[])],
            col_widths=[W*0.15, W*0.08, W*0.25, W*0.52],
        ),

        Paragraph("Geolocation", h2_style),
        section_table(["Field", "Value"], [
            ["Public IP",    g.get("public_ip","")],
            ["Country",      f"{g.get('country','')} ({g.get('country_code','')})"],
            ["Region",       g.get("region","")],
            ["City",         g.get("city","")],
            ["Coordinates",  f"Lat {g.get('latitude',0)}, Lon {g.get('longitude',0)}"],
            ["Timezone",     g.get("timezone","")],
            ["ISP",          g.get("isp","")],
            ["ASN",          g.get("asn","")],
            ["Proxy/VPN",    "YES" if g.get("is_proxy") else "No"],
            ["Hosting/DC",   "YES" if g.get("is_hosting") else "No"],
        ], col_widths=col2),
    ]

    doc.build(story)
